# Generated by Django 4.2 on 2023-04-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_album_genre_remove_album_artist_alter_album_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(to='myapp.song'),
        ),
    ]
