# Generated by Django 4.2 on 2023-04-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_album_name_alter_artist_name_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
