# Generated by Django 4.2 on 2023-04-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='myapp.artist'),
        ),
    ]
